# Stage 1: Build the Angular application
FROM node:krypton-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

RUN npm run build

# Stage 2: Serve with Nginx
FROM nginx:mainline-alpine AS serve

COPY nginx.conf /etc/nginx/nginx.conf

COPY --from=build /app/dist/CodeClique/browser /usr/share/nginx/html

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]