FROM ghcr.io/astral-sh/uv:python3.13-bookworm-slim

WORKDIR /app

COPY . .

RUN uv sync --frozen --no-cache

EXPOSE 3000

CMD ["/app/.venv/bin/fastapi", "run", "src/main.py", "--host", "0.0.0.0", "--port", "3000", "--proxy-headers"]