"""Add external_id to menu items

Revision ID: 467833cc429e
Revises: 003
Create Date: 2026-01-28 07:12:39.116788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '467833cc429e'
down_revision: Union[str, Sequence[str], None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('external_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_categories_external_id'), 'categories', ['external_id'], unique=True)
    op.add_column('menu_items', sa.Column('external_id', sa.String(), nullable=True))
    op.alter_column('menu_items', 'items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_menu_items_external_id'), 'menu_items', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu_items_external_id'), table_name='menu_items')
    op.alter_column('menu_items', 'items',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('menu_items', 'external_id')
    op.drop_index(op.f('ix_categories_external_id'), table_name='categories')
    op.drop_column('categories', 'external_id')
    # ### end Alembic commands ###
